Textarea component with tests
JadRizk/vue3-auth pull request #17
Opened 2021-04-11 03:18 UTC by RizaHKhan

#16

2021-04-12 19:46 UTC, JadRizk approved these changes

2021-04-12 19:46 UTC, JadRizk commented on src/components/atoms/BaseTextArea.atom.vue
> +  id: string
This is causing a TS error on the `setup` function.

Try this instead: 
```suggestion
id?: string;
```

2021-04-12 19:46 UTC, JadRizk commented on src/components/atoms/BaseTextArea.atom.vue
> +  name: 'BaseTextInput',
```suggestion
  name: 'BaseTextArea',
```

2021-04-12 19:48 UTC, JadRizk requested changes
I believe that the issue with the `id` param is causing the Netlify checks to fail. 

Maybe we should be fixing that first.

2021-04-12 20:46 UTC, RizaHKhan commented on src/components/atoms/BaseTextArea.atom.vue
> +  name: 'BaseTextInput',
omg silly mistake, sorry.

Corrected.

2021-04-13 19:05 UTC, JadRizk approved these changes
Sounds good 💥

2021-04-13 19:33 UTC, merged