Rkhan/vulidate verbiage
JadRizk/vue3-auth pull request #9
Opened 2021-04-08 20:56 UTC by RizaHKhan

#7

2021-04-08 20:57 UTC, RizaHKhan commented
@JadRizk I am not very proficient with Typescript yet, so I wanted to point out that use of the `any` type might not be to your liking. 

Used in the vuelidateRules.ts file.

2021-04-09 08:18 UTC, JadRizk requested changes

2021-04-09 14:32 UTC, RizaHKhan commented on src/services/vuelidateRules.ts
> +import { required, minLength, email, helpers } from '@vuelidate/validators'
That sounds better, adjusted.

2021-04-09 14:35 UTC, RizaHKhan commented on src/services/vuelidateRules.ts
> +    email: helpers.withMessage((v: any) => `Please enter a valid email`, email),
Adjustment made

2021-04-09 14:44 UTC, RizaHKhan commented on src/services/vuelidateRules.ts
> +}
adjustment made, definitely better.

2021-04-09 14:45 UTC, RizaHKhan commented
@JadRizk I made an adjustment to the login form to use the email and not the username. 
That seems to be standard convention and some of the logic was already referencing email.

2021-04-10 10:12 UTC, JadRizk approved these changes

2021-04-10 10:15 UTC, merged